config/environments/production.rb
I followed the instructions here:
https://www.lewagon.com/blog/setting-up-free-ssl-certificate-heroku
=> Added ssl configuration

app/controllers/matchings_controller.rb, test/controllers/matchings_controller_test.rb
added matching controller with empty index method. still need something to iterate over
=> Matchingindex

app/controllers/matchings_controller.rb, app/views/matchings/index.html.erb, config/routes.rb
added the view for the "your matches".
=> create view for 'your matches'

app/controllers/appointments_controller.rb, app/views/appointments/index.html.erb, config/routes.rb, test/controllers/appointments_controller_test.rb
ranzig investor's calendar view done (without calendar)
=> Calendar view

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_navbar.scss, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb
=> navbar changes and sign in

app/controllers/viewings_controller.rb, app/views/viewings/index.html.erb, config/routes.rb, db/schema.rb, test/controllers/viewings_controller_test.rb
just created the viewing's controller and viewing's view
=> add viewing's view

app/models/availability.rb, app/models/user.rb
Added validations to availability and user models 🎉
=> Added validations to availability and user models

.gitignore, Gemfile, Gemfile.lock, app/models/user.rb, app/uploaders/photo_uploader.rb, db/migrate/20190828143843_add_photo_to_users.rb, db/schema.rb
Cloudinary is now accessible in our rails app 👻
=> Cloudinary

app/views/devise/registrations/new.html.erb
=> form style changes

app/assets/stylesheets/application.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
1) new sign in page (=is for conference attendees)
2) new sign up page (=is for conference organizers)
3) button font-weight is now bold (globally)
=> sign in / sign up + btn

app/models/user.rb, db/seeds.rb
1) add dummy user to seed file
2) delete verification  (presence true) on user to allow for empty users (only email, pwd & name are now requried)
=> seed file + user model changes

app/models/user.rb
trimmed down validations in the user profile
Only the name, email and pwd are required now to create a user
=> final fix validations

app/controllers/appointments_controller.rb, app/views/appointments/index.html.erb, app/views/layouts/application.html.erb, db/seeds.rb
Style still missing, coming next, pmt!
=> Calendar logic works, seeds slightly changed

app/assets/stylesheets/components/_appointments.scss, app/assets/stylesheets/components/_index.scss, app/controllers/meetings_controller.rb, app/models/user.rb, app/views/appointments/index.html.erb, app/views/meetings/index.html.erb, db/seeds.rb
=> Your matches logic

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> Navbar changes 3444

app/controllers/meetings_controller.rb, app/views/meetings/index.html.erb, db/seeds.rb
Now the likes logic works, i.e. the selection view is split up in likes and matches.
=> Selection view split logic between matches and likes

app/controllers/pages_controller.rb, db/migrate/20190827092453_add_details_to_users.rb, db/migrate/20190902100632_change_stages_type_in_users.rb, db/migrate/20190902101712_add_stages_array_to_users.rb, db/migrate/20190902103357_add_selling_array_to_users.rb, db/migrate/20190902104001_remove_sectors_from_users.rb, db/migrate/20190902104044_add_sectors_array_to_users.rb, db/migrate/20190902104146_remove_launch_status_from_users.rb, db/migrate/20190902104231_add_launch_status_array_to_users.rb, db/migrate/20190902130025_add_funds_raised_to_users.rb, db/migrate/20190902130103_add_number_of_employees_to_users.rb, db/schema.rb
changed strings to arrays, made pages controller work and added two iems to the users table
=> made profile form work + schema changes

app/views/pages/home.html.erb, db/migrate/20190827092453_add_details_to_users.rb, db/migrate/20190902101712_add_stages_array_to_users.rb, db/migrate/20190902103357_add_selling_array_to_users.rb, db/migrate/20190902104044_add_sectors_array_to_users.rb, db/migrate/20190902104231_add_launch_status_array_to_users.rb, db/schema.rb
added to the relevant columns the datatype arrays
=> cleaned the db mess

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_appointments.scss, app/assets/stylesheets/components/_index.scss, app/controllers/appointments_controller.rb, app/controllers/pages_controller.rb, app/javascript/packs/application.js, app/views/appointments/index.html.erb, db/migrate/20190902135353_add_meeting_spot_to_users.rb, db/schema.rb
Default meeting spot works now
=> Default meeting spot works now

app/views/devise/sessions/new.html.erb
=> changed text on sign in page

app/controllers/attendances_controller.rb
added the filter to the matching site that corresponds to the current_user.profile
=> filtering added

app/controllers/matchings_controller.rb, app/controllers/meetings_controller.rb, app/services/matcher_service.rb
logic works now: if a match is generated, it is being removed from the likes
=> logic works now: if a match is generated, it is being removed from the likes

app/assets/stylesheets/components/_appointments.scss, app/controllers/appointments_controller.rb, app/controllers/meetings_controller.rb, app/views/appointments/index.html.erb
schedule now view for startups in appointments: UI izz da
=> schedule now view for startups in appointments: UI izz da

app/assets/stylesheets/components/_matching-card.scss, app/views/meetings/_meeting_investor_card.html.erb, app/views/meetings/_meeting_startup_card.html.erb, app/views/meetings/index.html.erb
- added .join to arrays
- changed 'no matches text'
- aligned items
=> cosmetics on selection view

app/assets/stylesheets/components/_alert-match.scss, app/assets/stylesheets/components/_alert.scss, app/javascript/packs/application.js, app/views/attendances/index.html.erb
It's working! :-) You can close the alert <3
=> added a working dismiss button to the flash alert

app/assets/stylesheets/components/_matching-card.scss, app/assets/stylesheets/components/_user-card.scss, app/views/attendances/index.html.erb
- lower box-shadow (both matching & selection view)
- changed dislike button to "pass only"
=> style changes (shadow + "pass")

app/views/appointments/index.html.erb, app/views/pages/home.html.erb, app/views/shared/_logged_in_home.html.erb, app/views/shared/_show-details.html.erb, app/views/shared/_sign_in_home.html.erb
homepage: remove login-button on homepage when already logged-in - done
=> Calendar view division

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_matching-card.scss, app/views/attendances/index.html.erb
- show 1 card a time
- add a counter (how many left)
- add text with links to other pages when no profiles left
- fix headline bug
- remove truncate
=> matching view changes

Gemfile, app/assets/javascripts/application.js, app/controllers/viewings_controller.rb, app/views/attendances/index.html.erb, app/views/shared/_investor-profile.html.erb, app/views/viewings/create_dislike.js.erb, app/views/viewings/create_like.js.erb, package-lock.json, package.json, yarn.lock
Although the branch's name may suggest differently, I added just some ajax to the attendances view
=> deleted the comments in the controller

app/assets/stylesheets/components/_matching-card.scss, app/assets/stylesheets/components/_user-card.scss, app/views/attendances/index.html.erb, app/views/shared/_navbar.html.erb, app/views/viewings/create_like.js.erb
- removed JS for matching view (didn't work)
- changed font size for "no profiles left"
=> fix matching + style changes

public/404.html, public/422.html, public/500.html
changed text in 404, 422 and 500 page
=> 404, 422, 500 page done

app/assets/stylesheets/components/_appointments.scss, app/assets/stylesheets/components/_user-card.scss, app/controllers/availability_meetings_controller.rb, app/views/appointments/index.html.erb, app/views/availabilities/create.html.erb, app/views/availabilities/new.html.erb, app/views/events/index.html.erb, app/views/meetings/_meeting_investor_card.html.erb
1. Once scheduled, you cannot schedule again
2. it now updates status to "Scheduled" everywhere once a meeting is scheduled
=> New changes 490hhj2

app/assets/javascripts/application.js, app/assets/stylesheets/components/_appointments.scss, app/assets/stylesheets/components/_calendar_info.scss, app/assets/stylesheets/components/_index.scss, app/javascript/packs/application.js, app/javascript/packs/slot.js, app/views/appointments/index.html.erb, app/views/shared/_show-details.html.erb
Company's details are shown when you click on the time slot
=> Appointments split

app/views/appointments/index.html.erb
added some if statements, so that the appointment page can be shown although there are no meetings.
=> added the if statement meetings present?
